schema_version: 1

context:
  name: tensorpotential
  version: "0.2.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/ICAMS/TensorPotential/archive/8776209fec766bfee4268e7e0b82a4ddb88d7cbe.tar.gz
  sha256: f8db5a18af47d066373bd708f3650b58843377f06aed7569bdb5be1b33e0aef5
  patches:
    - python.patch

build:
  number: 5
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<3.13
    - scipy
    - tensorflow
    - numpy
    - pandas
    - ase

tests:
  - python:
      imports:
        - tensorpotential
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: TensorFlow based interface for ML potentials development, fitting and evaluation
  description: |
    Tensorpotential is a TensorFlow based tool for development, fitting
    ML interatomic potentials from electronic structure calculations data
    and perform computations using these potentials.
  license: ADSL
  license_file: ASL.txt
  homepage: https://github.com/ICAMS/TensorPotential
  repository: https://github.com/ICAMS/TensorPotential
  documentation: https://github.com/ICAMS/TensorPotential

extra:
  recipe-maintainers:
    - jan-janssen
